### ISSUE TITLE
ndviz fig

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#24]
3 panel figure
All subpanels are screenshots using these web-services. 
1. enables overlaying annotation layers and querying them for metadata details (eg,  http://brainviz1.cs.jhu.edu/ndv/kharris15apical/em,ramon_test/3/507/469/90/)
2. multispectral data (eg, http://brainviz1.cs.jhu.edu/ndv/project/Aratome15c_S17_W10/1/5818/527/0/), including various blending and other color operations
3. time-series data (eg, http://viz.neurodata.io/freeman14/)

**Comment by alexbaden** [comment]
There are three versions of multispectral data in NDV:
1. Current NDV Version -- brightness / contrast don't really do much, color is done via ndstore, and blending is done via css, is slow, and isn't "additive" (not what you want for multi-spectral). 
2. Caman NDV -- blends the loaded tile layers into a new layer using javascript. Allows us to do dynamic recoloring, replaces brightness / contrast with "min / max" that allow you to resample the underlying tiles (which is what AT peeps seem to want), and does additive (and all other types) of blending. But, is highly memory intensive and a tad slow. Is currently pretty stable.
3. WebGL NDV -- Similar to 2, but it solves the problem of doing things in javascript by rendering underlying tiles as textures using WebGL. More powerful than 2, and also [theoretically] much faster and less memory usage (note: also still fully mobile compatible, one could argue WebGL is made more popular by the smartphone). Currently still working on proof of concept.

If you were publishing tomorrow, I'd say use 1. If not, 2 is technically much better, but the memory usage and speed put a damper on things. I think 3 is the best option, but I'm still trying to produce a proof of concept (to be fair, I started this morning) and am not sure if that's an hours, days, or week task. 

I think what I will do is produce a figure for 1. If 3 works before the paper goes out, I can really quickly update the figure. Otherwise, we'll just downplay multi-spectral a bit in the text, since the implementation will likely change (either optimized 2 or 3 to make it at all usable). 

( @randalburns )

**Comment by jovo** [comment]
sounds awesome.

**Comment by alexbaden** [comment]
Figures produced using WebGL version. The draft is in the paper and I'm working on a lucidchart sub-paneled version now.
